<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="10" total="16" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Regression" duration-ms="81946" started-at="2021-08-29T09:28:47Z" finished-at="2021-08-29T09:30:09Z">
    <groups>
    </groups>
    <test name="XYZ-functionality" duration-ms="81946" started-at="2021-08-29T09:28:47Z" finished-at="2021-08-29T09:30:09Z">
      <class name="co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore2">
        <test-method status="SKIP" signature="testCaseName()[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore2@6500df86]" name="testCaseName" is-config="true" duration-ms="0" started-at="2021-08-29T09:29:16Z" finished-at="2021-08-29T09:29:16Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode of test case is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode of test case is set to N
at co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore2.testCaseName(LoginToMyStore2.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseName -->
        <test-method status="SKIP" signature="loginToMyStore2(java.util.Hashtable)[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore2@6500df86]" name="loginToMyStore2" duration-ms="0" started-at="2021-08-29T09:29:16Z" data-provider="data_Collection" finished-at="2021-08-29T09:29:16Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode of test case is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode of test case is set to N
at co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore2.testCaseName(LoginToMyStore2.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStore2 -->
      </class> <!-- co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore2 -->
      <class name="co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore4">
        <test-method status="SKIP" signature="testCaseName()[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore4@59ec2012]" name="testCaseName" is-config="true" duration-ms="2" started-at="2021-08-29T09:29:48Z" finished-at="2021-08-29T09:29:48Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode of test case is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode of test case is set to N
at co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore4.testCaseName(LoginToMyStore4.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseName -->
        <test-method status="SKIP" signature="loginToMyStore4(java.util.Hashtable)[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore4@59ec2012]" name="loginToMyStore4" duration-ms="0" started-at="2021-08-29T09:29:48Z" data-provider="data_Collection" finished-at="2021-08-29T09:29:48Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode of test case is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode of test case is set to N
at co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore4.testCaseName(LoginToMyStore4.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStore4 -->
      </class> <!-- co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore4 -->
      <class name="co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore3">
        <test-method status="PASS" signature="testCaseName()[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore3@402a079c]" name="testCaseName" is-config="true" duration-ms="0" started-at="2021-08-29T09:29:16Z" finished-at="2021-08-29T09:29:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseName -->
        <test-method status="PASS" signature="loginToMyStore3(java.util.Hashtable)[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore3@402a079c]" name="loginToMyStore3" duration-ms="25339" started-at="2021-08-29T09:29:16Z" data-provider="data_Collection" finished-at="2021-08-29T09:29:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Name=Siva, Page_Title=My Store, Email_ID=siva@gmail.com, Sr.No=1, Page_Text=CREATE AN ACCOUNT, City=HYD, ContactNo=1234567893}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStore3 -->
      </class> <!-- co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore3 -->
      <class name="co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore6">
        <test-method status="SKIP" signature="testCaseName()[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore6@2f686d1f]" name="testCaseName" is-config="true" duration-ms="0" started-at="2021-08-29T09:30:09Z" finished-at="2021-08-29T09:30:09Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode of test case is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode of test case is set to N
at co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore6.testCaseName(LoginToMyStore6.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseName -->
        <test-method status="SKIP" signature="loginToMyStore6(java.util.Hashtable)[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore6@2f686d1f]" name="loginToMyStore6" duration-ms="0" started-at="2021-08-29T09:30:09Z" data-provider="data_Collection" finished-at="2021-08-29T09:30:09Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode of test case is set to N]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode of test case is set to N
at co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore6.testCaseName(LoginToMyStore6.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStore6 -->
      </class> <!-- co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore6 -->
      <class name="co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore5">
        <test-method status="PASS" signature="testCaseName()[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore5@4cf777e8]" name="testCaseName" is-config="true" duration-ms="0" started-at="2021-08-29T09:29:48Z" finished-at="2021-08-29T09:29:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseName -->
        <test-method status="FAIL" signature="loginToMyStore5(java.util.Hashtable)[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore5@4cf777e8]" name="loginToMyStore5" duration-ms="14614" started-at="2021-08-29T09:29:48Z" data-provider="data_Collection" finished-at="2021-08-29T09:30:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Name=SivaTC5, Page_Title=My St, Email_ID=siva@gmail.com, Sr.No=1, Page_Text=CREATE AN ACCOUNT, City=HYD, ContactNo=1234567893}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My St] but found [My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My St] but found [My Store]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at co.in.bymat.projectName.ModuleName.pages.HomePage.createAnAccount(HomePage.java:16)
at co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore5.loginToMyStore5(LoginToMyStore5.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStore5 -->
      </class> <!-- co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore5 -->
      <class name="co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore">
        <test-method status="PASS" signature="initialization()[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore@42dafa95]" name="initialization" is-config="true" duration-ms="599" started-at="2021-08-29T09:28:47Z" finished-at="2021-08-29T09:28:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialization -->
        <test-method status="PASS" signature="testCaseName()[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore@42dafa95]" name="testCaseName" is-config="true" duration-ms="0" started-at="2021-08-29T09:28:47Z" finished-at="2021-08-29T09:28:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseName -->
        <test-method status="PASS" signature="loginToMyStore(java.util.Hashtable)[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore@42dafa95]" name="loginToMyStore" duration-ms="22980" started-at="2021-08-29T09:28:47Z" data-provider="data_Collection" finished-at="2021-08-29T09:29:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Name=Deepali, Page_Title=My Store, Email_ID=Deepali@gmail.com, Sr.No=1, Page_Text=CREATE AN ACCOUNT, City=Noida, ContactNo=98582345632}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToMyStore -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore@42dafa95]" name="endReport" is-config="true" duration-ms="220" started-at="2021-08-29T09:30:09Z" finished-at="2021-08-29T09:30:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- co.in.bymat.projectName.ModuleName.testCases.LoginToMyStore -->
    </test> <!-- XYZ-functionality -->
  </suite> <!-- Regression -->
</testng-results>
